WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER ORACLE_SOURCE CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP USER ORACLE_TARGET CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

CREATE USER ORACLE_SOURCE IDENTIFIED BY oracle_source_pass QUOTA UNLIMITED ON USERS;
CREATE USER ORACLE_TARGET IDENTIFIED BY oracle_target_pass QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER, UNLIMITED TABLESPACE TO ORACLE_SOURCE;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER, UNLIMITED TABLESPACE TO ORACLE_TARGET;

CREATE TABLE ORACLE_SOURCE.USERS (
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR2(100 CHAR) NOT NULL,
  AGE NUMBER(3),
  CREATED_AT DATE NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ORACLE_SOURCE_USERS_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (CREATED_AT) (
  PARTITION P202401 VALUES LESS THAN (DATE '2024-02-01'),
  PARTITION P202402 VALUES LESS THAN (DATE '2024-03-01'),
  PARTITION PMAX VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX ORACLE_SOURCE.IDX_USERS_CREATED_AT ON ORACLE_SOURCE.USERS (CREATED_AT);

INSERT INTO ORACLE_SOURCE.USERS (ID, NAME, AGE, CREATED_AT) VALUES (1, 'Alice Oracle', 31, DATE '2024-01-15');
INSERT INTO ORACLE_SOURCE.USERS (ID, NAME, AGE, CREATED_AT) VALUES (2, 'Bob Oracle', 29, DATE '2024-02-18');
INSERT INTO ORACLE_SOURCE.USERS (ID, NAME, AGE, CREATED_AT) VALUES (3, 'Cara Oracle', 35, DATE '2024-03-12');

CREATE TABLE ORACLE_TARGET.USERS (
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR2(100 CHAR) NOT NULL,
  AGE NUMBER(3),
  CREATED_AT DATE NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ORACLE_TARGET_USERS_PK PRIMARY KEY (ID)
);

CREATE INDEX ORACLE_TARGET.IDX_USERS_CREATED_AT ON ORACLE_TARGET.USERS (CREATED_AT);

INSERT INTO ORACLE_TARGET.USERS (ID, NAME, AGE, CREATED_AT) VALUES (1, 'Legacy Oracle', 99, DATE '2024-01-15');
INSERT INTO ORACLE_TARGET.USERS (ID, NAME, AGE, CREATED_AT) VALUES (99, 'Sentinel Oracle', 77, DATE '2023-12-31');

COMMIT;
